'use client';
import {useState} from 'react';
import {BookOpen, FlaskConical, Link2, ShieldCheck} from 'lucide-react';
import {useLedger} from '@/lib/ledger';
import deployment from '@/artifacts/deployment.json';

export default function Home(){
 const l=useLedger(deployment.address); const [id,setId]=useState('STUDY-001'); const [title,setTitle]=useState('Replication audit'); const [claim,setClaim]=useState('The published method can be reproduced from the linked artifacts.'); const [paper,setPaper]=useState('https://www.iana.org/help/example-domains'); const [code,setCode]=useState('https://github.com/rankoo21/ReproStamp'); const [data,setData]=useState('https://example.com/'); const [record,setRecord]=useState<any>(null);
 async function submit(){await l.write('submit_study',[id,title,claim,paper,code,data],async()=>true)}
 async function audit(){const sid=id.trim().toUpperCase(); await l.write('audit_study',[sid],async()=>{const r=await l.read('get_study',[l.account,sid]);setRecord(r);return r?.status==='AUDITED'})}
 return <main><header><div className="brand"><BookOpen/><span>REPRO<span>STAMP</span></span></div><div className="tag">RESEARCH REPRODUCIBILITY / STUDIONET</div><button className="connect" onClick={l.connect}>{l.account?l.account.slice(0,6)+'…'+l.account.slice(-4):'Connect wallet'}</button></header><section className="hero"><div><p className="kicker">A CONSENSUS LAB NOTEBOOK</p><h1>Make claims<br/><i>repeatable.</i></h1><p>ReproStamp asks independent validators to fetch a paper, code artifact, and dataset page, then preserve the exact bytes behind a reproducibility verdict.</p></div><div className="seal"><FlaskConical/><b>3 sources</b><small>Validator-fetched<br/>SHA-256 anchored</small></div></section><section className="bench"><aside><span>01 / STUDY CARD</span><h2>Register a study</h2><label>Study ID<input value={id} onChange={e=>setId(e.target.value)}/></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Claim<textarea value={claim} onChange={e=>setClaim(e.target.value)}/></label></aside><div className="evidence"><h3>Evidence shelf</h3><label><Link2/> PAPER URL<input value={paper} onChange={e=>setPaper(e.target.value)}/></label><label><Link2/> CODE URL<input value={code} onChange={e=>setCode(e.target.value)}/></label><label><Link2/> DATA URL<input value={data} onChange={e=>setData(e.target.value)}/></label><div className="actions"><button onClick={submit} disabled={!l.account||l.busy}>Submit study ↗</button><button onClick={audit} disabled={!l.account||l.busy}>Audit with consensus <ShieldCheck size={16}/></button></div><p className="status">{l.message||'Connect your wallet to write a permanent study card.'}</p></div></section>{record&&<section className="result"><div><span>FINAL VERDICT</span><h2>{record.verdict}</h2><p>{record.findings?.join(' ')}</p></div><div className="digests"><span>BYTE RECEIPTS</span>{record.digests?.map((d:string)=><code key={d}>{d}</code>)}</div></section>}<footer>ReproStamp · public evidence, private keys stay in your wallet</footer></main>}
